### ISSUE TITLE
Incorrect register definitions

### ISSUE THREAD

**Issue by ohoc** [ashlaban/dw1000-driver#1]
Hi,

First, let me thank you for the dw1000-driver, it is really useful!

I just wanted to let you know that there is a small error in some fields definitions of the CHAN_CTRL register. I attached a patch providing the fix.

Best regards,

Olivier

[0001-Fix-some-definitions-in-CHAN_CTRL-register.zip](https://github.com/ashlaban/dw1000-driver/files/4474486/0001-Fix-some-definitions-in-CHAN_CTRL-register.zip)

**Comment by ashlaban** [comment]
Hi,

Thanks for the kind words.

If you would kindly submit the patch as a PR instead that would be much appreciated.

**Comment by ashlaban** [comment]
Again, thanks for pointing out the issue. Checking through the documentation I found another error in that register definition.
